// services 统一出口：装配层只 import 这里，不直接触碰 @tauri-apps/api。

import * as usageService from './usageService'
import * as collectorService from './collectorService'
import * as windowService from './windowService'
import * as exportService from './exportService'
import * as dataService from './dataService'
import * as subscriptionService from './subscriptionService'
import * as updateService from './updateService'
import * as autostartService from './autostartService'
import * as taskService from './taskService'
import * as projectService from './projectService'
import * as timelineService from './timelineService'
import * as events from './events'

export { usageService, collectorService, windowService, exportService, dataService, subscriptionService, updateService, autostartService, taskService, projectService, timelineService, events }
export type { TimelineResult, TimelineProject, TimelineCell, TimelineSession, AttentionItem, AttentionState } from './timelineService'
export { inTauri } from './tauri'
export type { WindowVisibility, OrbDockState } from './windowService'
export type { UsageResult, UsageRow, SourceSummary, ExportResult, QueryOptions } from './types'
export type { DayRange, DaySpan, TaskFilters, TaskSort, TaskRow, TaskPage, TaskTurn, GapHistogram, GapBucket, IdleThresholdInfo, IdleThresholdApplied } from './types'
export type { ProjectGroupBy, ProjectMetric, TaskSortField } from './contract'
export type { BreakdownDay, BreakdownSlice, ChangedKeys } from './contract'
export type { CreditSummary, CreditModelDaySlice } from './usageService'
export type { RangeSeriesQuery, RangeSeriesResult, RangeSeriesPoint, EffortSeriesQuery } from './usageService'
export type { DataInfo } from './dataService'
export type { SubscriptionSnapshot, CredentialInfo, QuotaWindow, SubscriptionPlatform, BoostConfig, PlatformIdleState } from './subscriptionService'
export type { UpdateCheck, UpdateProgress } from './updateService'
export type { AutostartInfo } from './autostartService'
export type { ProjectMetaRow, ProjectMetaList, ProjectStatus, ScratchRule, ScratchRuleInfo, WriteResult } from './projectService'
